### ISSUE TITLE
Carthage build

### ISSUE THREAD

**Issue by Gvardia** [rubygarage/media-watermark#14]
I have that message.
 
Skipped building media-watermark due to the error:
Dependency "media-watermark" has no shared framework schemes for any of the platforms: iOS

Is it possible to build library with Carthage?

**Comment by olivanov** [comment]
Hi,

It would be great to add Carthage support!

**Comment by plzen** [comment]
Hello. 

I marked this issue as enhancement. We are working on Carthage support and will release new version in the nearest future.

Thank you for support.
