### ISSUE TITLE
Can't even build this framework

### ISSUE THREAD

**Issue by pateljay43** [rubygarage/media-watermark#17]

**Comment by plzen** [comment]
Hello @pateljay43.
Could you provide more details? It will be helpful for reproducing your issue.

**Comment by pateljay43** [comment]
`tracks(withMediaType: AVMediaType.video)`
this is where I get a compile error -> `Cannot call value of non-function type '[AVAssetTrack]'`

**Comment by plzen** [comment]
Looks like you tried to use Swift 3.2 to build framework. Try to change Swift version to 4.0.
