### ISSUE TITLE
Error installing pod

### ISSUE THREAD

**Issue by jesusmartinezd** [rubygarage/media-watermark#18]
[!] Error installing MediaWatermark
[!] /usr/bin/git clone https://github.com/rubygarage-ios/MediaWatermark.git /var/folders/tp/n1gccmt510s5v3r20krnv1b80000gn/T/d20180316-11209-z3x71m --template= --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/tp/n1gccmt510s5v3r20krnv1b80000gn/T/d20180316-11209-z3x71m'...
remote: Repository not found.
fatal: repository 'https://github.com/rubygarage-ios/MediaWatermark.git/' not found

**Comment by plzen** [comment]
You tried to install version 0.1.0. We've fixed this in next releases.

Try `pod 'MediaWatermark', '~> 0.2'`

**Comment by jesusmartinezd** [comment]
In pod file: 

pod 'MediaWatermark','~> 0.2'

but returns me on "pod install":

_[!] CocoaPods could not find compatible versions for pod "MediaWatermark":
  In Podfile:
    MediaWatermark (~> 0.2)

None of your spec sources contain a spec satisfying the dependency: `MediaWatermark (~> 0.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default._

**Comment by plzen** [comment]
Try to update pod repo:
```
pod repo update
```
