### ISSUE TITLE
Add rotation to UIImage 

### ISSUE THREAD

**Issue by trollblocks** [rubygarage/media-watermark#25]
Hello I  want to add rotation for picture baked  on my video but it's look like . MediaElement does not support it 
 is it possible for you to add this feature please ? 

thank you .

**Comment by jowkame** [comment]
Media-watermark does not support custom image rotation at the moment. Also you can simply edit source image before adding it to the asset. But we'll add this improvement to our roadmap.

**Comment by trollblocks** [comment]
clever !!  ok i got it  , i will do it thank you .
