### ISSUE TITLE
Android equivalent library

### ISSUE THREAD

**Issue by pravingaikwad123** [rubygarage/media-watermark#29]
This is not an issue.

Is there any android equivalent library for Media-Watermark which is as robust as this lib.

I have tried ffmpeg and LanSoSdk. Both taking too much time to add watermark to video.
Eg. 25 seconds for 8 seconds video, 1 min approx for 55 second video.

**Comment by plzen** [comment]
You can try to find something similar to this library here - https://android-arsenal.com. Or this repositories - https://github.com/search?q=awesome-android
